### DISCUSSION TITLE
My CI is not seeing my environment variables!

### DISCUSSION THREAD

**Discussion by thorwhalen** [i2mint/isee#24] [Q&A] [answered]
My tests are failing because the code doesn't see my environment variables, though I do have them in my "repository secrets".

Concrete example:

This part fails:

```
      - name: Pytest Validation
        uses: i2mint/isee/actions/pytest-validation@master
        with:
          root-dir: ${{ env.PROJECT_NAME }}
          paths-to-ignore: examples,scrap
```

where (currently) the `` contents [can be found here](https://github.com/i2mint/isee/blob/e3f69325562dfdc1aec2a8626d6862975c3a57b3/actions/pytest-validation/action.yml)

**Comment by thorwhalen** [comment, marked as answer]
## tldr;

Add this to the part of the CI that fails:

```
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
```

## details

To ensure that your GitHub Actions workflow can access the `KAGGLE_KEY` environment variable that you've stored in your repository secrets, you need to explicitly pass this secret to the workflow. Secrets are not passed to the runner environment by default for security reasons. 

Here's how you can modify your `ci.yml` file to include the `KAGGLE_KEY` environment variable:

```yaml
      - name: Pytest Validation
        uses: i2mint/isee/actions/pytest-validation@master
        with:
          root-dir: ${{ env.PROJECT_NAME }}
          paths-to-ignore: examples,scrap
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
```

In this snippet, the `env` section under the `Pytest Validation` step is used to set environment variables for that step. Here, `KAGGLE_KEY` is set to the value of the secret `KAGGLE_KEY` from your repository's secrets.

Remember, for this to work:

1. The secret `KAGGLE_KEY` must be correctly set in your repository's settings under the 'Secrets' section.

2. The GitHub Actions runner needs to have the appropriate permissions to access repository secrets. This is usually the case by default, but if you're using a self-hosted runner or have modified the default permissions, you may need to adjust them.

3. Ensure that your code is correctly configured to use the `KAGGLE_KEY` environment variable.

By making this change, your GitHub Actions workflow should be able to access the `KAGGLE_KEY` environment variable and use it during the `Pytest Validation` step.

**Reply by thorwhalen** [reply]
My ci.yml is actually generated by a template that remains the same for all my projects. In this template, all variations between projects happen via such variables as `${{ env.PROJECT_NAME }}` etc. 

The solution you propose obliges me to edit my copy of the template, which I don't want to do because it makes it harder for me to maintain. 

Is there a way for me to change to include something in the template that will have the effect that anytime the code will look for some environment variable, it will know to look for it in secrets (or some other place that is particular to the repository)?

**Reply by thorwhalen** [reply]
To create a flexible GitHub Actions workflow template that automatically maps environment variables to secrets without requiring per-repository modifications, you can use a dynamic approach to set all secrets as environment variables. However, GitHub Actions does not directly support dynamically mapping all secrets to environment variables due to security reasons. Each secret must be explicitly declared.

That said, there is a workaround using a script within your workflow. You can write a shell script step that reads a predefined list of environment variable names (which are common across your projects) and sets them using the corresponding secrets. Here's an example approach:

1. **Define a list of common environment variable names** in your workflow file. These are the names you expect to use across different projects.

2. **Write a script in your workflow** that loops through these variable names, checks if a secret with the same name exists, and sets an environment variable with its value.

Here's a modified snippet of your `ci.yml` to illustrate this:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMON_ENV_VARS: 'KAGGLE_KEY,ANOTHER_VAR,SOME_OTHER_VAR'
    steps:
      - name: Set Environment Variables from Secrets
        run: |
          for var in ${COMMON_ENV_VARS//,/ }; do
            if [ ! -z "${{ secrets[var] }}" ]; then
              echo "$var=${{ secrets[var] }}" >> $GITHUB_ENV
            fi
          done

      - name: Pytest Validation
        uses: i2mint/isee/actions/pytest-validation@master
        with:
          root-dir: ${{ env.PROJECT_NAME }}
          paths-to-ignore: examples,scrap
        # Now, the environment variables are set globally for this job
```

In this script:

- `COMMON_ENV_VARS` is a comma-separated list of environment variable names.
- The `for` loop iterates through each name, checks if a secret with that name exists, and if so, sets an environment variable with its value.

Remember, this approach requires that the secret names match the environment variable names exactly. Also, be aware that while this method can improve maintenance efficiency, it might pose a security risk by potentially exposing secrets if not handled cautiously.

If this solution does not meet your security standards, or if you have a large number of variable names that vary significantly across projects, you might need to consider a different approach, possibly involving external scripts or more complex GitHub Actions configurations.
