### ISSUE TITLE
Automate little dev tasks and make them consistent.

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/isee#10]
I'll take one as an example. 

_For a given repository, I could specify a default label that would be used for any new issues I create. Though it's a small overhead, it's just one of those "one more thing to click" that can become annoying._ (posted on [statckoverflow](https://stackoverflow.com/questions/66912157/how-to-automatically-add-default-label-when-making-a-github-issue))

I've tried that answer, but it failed for me (said I didn't provide a github_token (though I see it in secrets).

Note: Apparently, you can't use `GITHUB_TOKEN` as an environment name (see https://github.community/t/all-github-actions-suddenly-failing-with-github-token-secret-does-not-exist/16108). I used `GH_TOKEN`

My `.workflows/main.yml` is:

```

name: Add Label

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          labels: enhancement
```
