### ISSUE TITLE
Fix pytest-validation action to properly ignore specified directories

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/isee#32]
## Issue Description

The current `pytest-validation` GitHub Action doesn't completely prevent pytest from importing modules in ignored directories specified via the `paths-to-ignore` parameter. When using the action with directories like `_resources` that contain imports not available in the CI environment, it still fails with import errors despite being in the ignore list.

## Current Behavior

When specifying directories in `paths-to-ignore` (e.g., `_resources`), the action only adds `--ignore=root-dir/path` options to pytest. This approach has limitations:

1. Pytest still discovers modules in ignored directories during the collection phase
2. These modules are still imported, which causes failures if they depend on packages not available in CI
3. The `--ignore` flag alone doesn't completely prevent directory traversal

## Expected Behavior

The action should fully prevent pytest from discovering, importing, or running any tests in specified ignore paths.

## Proposed Solution

Enhance the action to use multiple pytest mechanisms to completely exclude ignored directories:

1. **Create a temporary pytest.ini with glob patterns**: Add pattern-based ignores for more robust exclusion
   ```bash
   echo "[pytest]" > pytest.ini
   echo "python_files = *.py" >> pytest.ini
   
   # Create addopts with ignore-glob patterns for each ignored path
   addopts="addopts ="
   IFS=',' read -ra paths <<< "${{ inputs.paths-to-ignore }}"
   for path in "${paths[@]}"
   do
       addopts+=" --ignore-glob=\"**/$path/**\""
   done
   
   echo "$addopts" >> pytest.ini
   ```

2. **Keep standard --ignore flags** for backward compatibility:
   ```bash
   # Add standard ignore option for each path
   options+=" --ignore=${{ inputs.root-dir }}/$path"
   ```

3. **Add `--confcutdir` option**: Prevent conftest.py files in ignored directories from being loaded
   ```bash
   options+=" --confcutdir=${{ inputs.root-dir }}"
   ```

4. **Improve logging**: Add echo statements to show both pytest.ini content and the final pytest command
   ```bash
   cat pytest.ini
   echo "Running: pytest $options ${{ inputs.root-dir }}"
   ```

## Implementation Details

The PR will modify the `pytest-validation/action.yml` file to implement these changes while maintaining backward compatibility with all existing parameters and usage patterns.

## Related Issues/PRs

None

## Additional Context

This issue affects projects that have development/test-only directories with dependencies not specified in the main package requirements, a common pattern for keeping the production dependency footprint minimal.

### Project Structure
```
my_project/
├── src/
│   └── core_module.py
├── tests/
│   └── test_core.py
├── _resources/
│   ├── __init__.py
│   └── dev_utils.py  # Imports special_package not in CI
└── setup.cfg  # Does not include special_package
```

### Content of _resources/dev_utils.py
```python
import special_package  # Not installed in CI

def helper_function():
    return special_package.some_function()
```

### GitHub Workflow File
```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Pytest Validation
      uses: i2mint/isee/actions/pytest-validation@master
      with:
        root-dir: my_project
        paths-to-ignore: _resources  # This should prevent _resources from being imported
```

### Current Error
```
ImportError: No module named 'special_package'
```

This occurs because despite _resources being in the ignore list, pytest still imports the module during collection.

## Labels
- bug
- github-actions
- ci
- testing
